<?php

/**
 * Main page controller
 *
 * @package FoldSnap
 */

declare(strict_types=1);

namespace FoldSnap\Controllers;

use FoldSnap\Core\Controllers\AbstractMenuPageController;
use FoldSnap\Core\Controllers\ControllersManager;

final class MainPageController extends AbstractMenuPageController
{
    /**
     * Class constructor
     */
    protected function __construct()
    {
        $this->pageSlug     = ControllersManager::MAIN_MENU_SLUG;
        $this->pageTitle    = __('FoldSnap', 'foldsnap');
        $this->menuLabel    = __('FoldSnap', 'foldsnap');
        $this->capatibility = 'upload_files';
        $this->menuPos      = 10;
        $this->parentSlug   = 'upload.php';

        add_action('foldsnap_render_page_content_' . ControllersManager::MAIN_MENU_SLUG, [$this, 'renderContent']);
    }

    /**
     * Render the React app mount point
     *
     * @return void
     */
    public function renderContent(): void
    {
        echo '<div id="foldsnap-app"></div>';
    }

    /**
     * Enqueue page scripts
     *
     * @return void
     */
    public function pageScripts(): void
    {
        $assetFile = FOLDSNAP_PATH . '/assets/js/foldsnap-admin.asset.php';
        if (!file_exists($assetFile)) {
            return;
        }

        /** @var array{dependencies: string[], version: string} $asset */
        $asset = require $assetFile; // @phpstan-ignore require.fileNotFound (build artifact generated by npm run build)

        wp_enqueue_script(
            'foldsnap-admin',
            FOLDSNAP_PLUGIN_URL . '/assets/js/foldsnap-admin.js',
            $asset['dependencies'],
            $asset['version'],
            true
        );

        wp_localize_script(
            'foldsnap-admin',
            'foldsnap_data',
            [
                'restUrl'   => rest_url('foldsnap/v1/'),
                'restNonce' => wp_create_nonce('wp_rest'),
            ]
        );
    }

    /**
     * Enqueue page styles
     *
     * @return void
     */
    public function pageStyles(): void
    {
        wp_enqueue_style('wp-components');
        wp_enqueue_style(
            'foldsnap-admin',
            FOLDSNAP_PLUGIN_URL . '/assets/css/foldsnap-admin.css',
            [],
            (string) filemtime(FOLDSNAP_PATH . '/assets/css/foldsnap-admin.css')
        );
    }
}
