<?php

/**
 * Media Library controller
 *
 * Enqueues FoldSnap assets exclusively on the Media Library screen (upload.php).
 * The sidebar container is created and positioned in the DOM by the JS bundle.
 *
 * @package FoldSnap
 */

declare(strict_types=1);

namespace FoldSnap\Controllers;

final class MediaLibraryController
{
    /** @var ?self */
    private static ?self $instance = null;

    /**
     * Return the singleton instance and register hooks on first call.
     *
     * @return self
     */
    public static function getInstance(): self
    {
        if (is_null(self::$instance)) {
            self::$instance = new self();
        }

        return self::$instance;
    }

    /**
     * Class constructor — registers WordPress hooks.
     */
    private function __construct()
    {
        add_action('admin_enqueue_scripts', [$this, 'enqueueAssets']);
    }

    /**
     * Enqueue scripts and styles only on the Media Library screen.
     *
     * @return void
     */
    public function enqueueAssets(): void
    {
        $screen = get_current_screen();
        if (null === $screen || 'upload' !== $screen->id) {
            return;
        }

        $assetFile = FOLDSNAP_PATH . '/assets/js/foldsnap-admin.asset.php';
        if (!file_exists($assetFile)) {
            return;
        }

        /** @var array{dependencies: string[], version: string} $asset */
        $asset = require $assetFile; // @phpstan-ignore require.fileNotFound (build artifact generated by npm run build)

        wp_enqueue_script(
            'foldsnap-admin',
            FOLDSNAP_PLUGIN_URL . '/assets/js/foldsnap-admin.js',
            $asset['dependencies'],
            $asset['version'],
            true
        );

        wp_localize_script(
            'foldsnap-admin',
            'foldsnap_data',
            [
                'restUrl'   => rest_url('foldsnap/v1/'),
                'restNonce' => wp_create_nonce('wp_rest'),
            ]
        );

        wp_enqueue_style('wp-components');
        wp_enqueue_style(
            'foldsnap-admin',
            FOLDSNAP_PLUGIN_URL . '/assets/css/foldsnap-admin.css',
            [],
            (string) filemtime(FOLDSNAP_PATH . '/assets/css/foldsnap-admin.css')
        );
    }
}
