<?php // phpcs:disable PSR1.Files.SideEffects.FoundWithSymbols

/**
 * Media Library controller
 *
 * Enqueues FoldSnap assets exclusively on the Media Library screen (upload.php).
 * The sidebar container is created and positioned in the DOM by the JS bundle.
 *
 * @package FoldSnap
 */

declare(strict_types=1);

namespace FoldSnap\Controllers;

defined('ABSPATH') || exit;

use FoldSnap\Services\TaxonomyService;
use FoldSnap\Utils\SanitizeInput;

final class MediaLibraryController
{
    /** @var ?self */
    private static ?self $instance = null;

    /**
     * Return the singleton instance and register hooks on first call.
     *
     * @return self
     */
    public static function getInstance(): self
    {
        if (is_null(self::$instance)) {
            self::$instance = new self();
        }

        return self::$instance;
    }

    /**
     * Class constructor — registers WordPress hooks.
     */
    private function __construct()
    {
        add_action('admin_enqueue_scripts', [$this, 'enqueueAssets']);
        add_filter('ajax_query_attachments_args', [$this, 'filterAttachmentsByFolder']);
        add_action('pre_get_posts', [$this, 'filterListModeByFolder']);
    }

    /**
     * Resolve the current media library mode (grid or list).
     *
     * Same logic as upload.php: URL parameter takes priority,
     * then user option, default 'grid'.
     *
     * @return string 'grid' or 'list'
     */
    public static function getMediaMode(): string
    {
        $urlMode = SanitizeInput::str(INPUT_GET, 'mode');
        if ('grid' === $urlMode || 'list' === $urlMode) {
            return $urlMode;
        }

        $userMode = get_user_option('media_library_mode', get_current_user_id());

        return is_string($userMode) && '' !== $userMode ? $userMode : 'grid';
    }

    /**
     * Filter media grid AJAX query by folder when foldsnap_folder_id is set.
     *
     * WordPress fires this filter on the query-attachments AJAX action
     * used by the native media grid. The JS subscribe() in index.js sets
     * foldsnap_folder_id on the Backbone collection props, which arrives
     * here as $_REQUEST['query']['foldsnap_folder_id'].
     *
     * @param array<string, mixed> $query WP_Query args for attachments.
     *
     * @return array<string, mixed> Modified query args.
     */
    public function filterAttachmentsByFolder(array $query): array
    {
        $folderId = SanitizeInput::toInt(
            SanitizeInput::INPUT_REQUEST,
            [
                'query',
                'foldsnap_folder_id',
            ],
            -1
        );

        if ($folderId >= 0) {
            $query['tax_query'] = TaxonomyService::buildFolderTaxQuery($folderId); // phpcs:ignore WordPress.DB.SlowDBQuery.slow_db_query_tax_query
        }
        return $query;
    }

    /**
     * Filter media list table query by folder (list mode).
     *
     * In list mode upload.php uses a standard WP_Query instead of the AJAX
     * query-attachments endpoint. The JS redirects to
     * upload.php?foldsnap_folder_id=ID when a folder is clicked.
     *
     * @param \WP_Query $query The current query.
     *
     * @return void
     */
    public function filterListModeByFolder(\WP_Query $query): void
    {
        if (!is_admin() || !$query->is_main_query() || 'attachment' !== $query->get('post_type')) {
            return;
        }

        // Only in list mode — grid mode loads via AJAX (filterAttachmentsByFolder).
        if ('list' !== self::getMediaMode()) {
            return;
        }

        $folderId = SanitizeInput::toInt(INPUT_GET, 'foldsnap_folder_id', -1);

        if ($folderId >= 0) {
            $query->set('tax_query', TaxonomyService::buildFolderTaxQuery($folderId)); // phpcs:ignore WordPress.DB.SlowDBQuery.slow_db_query_tax_query
        }
    }

    /**
     * Enqueue scripts and styles only on the Media Library screen.
     *
     * @return void
     */
    public function enqueueAssets(): void
    {
        $screen = get_current_screen();
        if (null === $screen || 'upload' !== $screen->id) {
            return;
        }

        $assetFile = FOLDSNAP_PATH . '/assets/js/foldsnap-admin.asset.php';
        if (!file_exists($assetFile)) {
            return;
        }

        /** @var array{dependencies: string[], version: string} $asset */
        $asset = require $assetFile; // @phpstan-ignore require.fileNotFound (build artifact generated by npm run build)

        wp_enqueue_script(
            'foldsnap-admin',
            FOLDSNAP_PLUGIN_URL . '/assets/js/foldsnap-admin.js',
            $asset['dependencies'],
            $asset['version'],
            true
        );

        wp_set_script_translations('foldsnap-admin', 'foldsnap', FOLDSNAP_PATH . '/languages');

        wp_localize_script(
            'foldsnap-admin',
            'foldsnap_data',
            [
                'restUrl'   => rest_url('foldsnap/v1/'),
                'mediaMode' => self::getMediaMode(),
            ]
        );

        wp_enqueue_script(
            'foldsnap-dragdrop',
            FOLDSNAP_PLUGIN_URL . '/assets/js/foldsnap-dragdrop.js',
            [
                'jquery',
                'jquery-ui-draggable',
                'jquery-ui-droppable',
                'wp-i18n',
                'foldsnap-admin',
            ],
            FOLDSNAP_VERSION,
            true
        );

        wp_set_script_translations('foldsnap-dragdrop', 'foldsnap', FOLDSNAP_PATH . '/languages');

        wp_enqueue_style('wp-components');
        wp_enqueue_style(
            'foldsnap-admin',
            FOLDSNAP_PLUGIN_URL . '/assets/css/foldsnap-admin.css',
            [],
            (string) filemtime(FOLDSNAP_PATH . '/assets/css/foldsnap-admin.css')
        );
    }
}
