export const STORE_NAME = 'foldsnap/folders';

export const ROOT_PARENT_ID = 0;

export const DEFAULT_PER_PAGE = 100;

export const SEARCH_PER_PAGE = 50;

export const ACTION_TYPES = {
	FETCH_CHILDREN_START: 'FETCH_CHILDREN_START',
	FETCH_CHILDREN_SUCCESS: 'FETCH_CHILDREN_SUCCESS',
	FETCH_CHILDREN_APPEND: 'FETCH_CHILDREN_APPEND',
	FETCH_CHILDREN_ERROR: 'FETCH_CHILDREN_ERROR',

	SET_ROOT_TOTALS: 'SET_ROOT_TOTALS',

	EXPAND_FOLDER: 'EXPAND_FOLDER',
	COLLAPSE_FOLDER: 'COLLAPSE_FOLDER',
	SET_EXPANDED_IDS: 'SET_EXPANDED_IDS',

	SET_SELECTED_FOLDER: 'SET_SELECTED_FOLDER',

	SET_SEARCH_QUERY: 'SET_SEARCH_QUERY',
	FETCH_SEARCH_START: 'FETCH_SEARCH_START',
	FETCH_SEARCH_SUCCESS: 'FETCH_SEARCH_SUCCESS',
	FETCH_SEARCH_APPEND: 'FETCH_SEARCH_APPEND',
	FETCH_SEARCH_ERROR: 'FETCH_SEARCH_ERROR',
	CLEAR_SEARCH: 'CLEAR_SEARCH',

	APPLY_AFFECTED_PARENTS: 'APPLY_AFFECTED_PARENTS',
	APPLY_PATH_TOTALS: 'APPLY_PATH_TOTALS',
	UPSERT_FOLDER: 'UPSERT_FOLDER',
	REMOVE_FOLDER: 'REMOVE_FOLDER',

	FETCH_MEDIA_START: 'FETCH_MEDIA_START',
	FETCH_MEDIA_SUCCESS: 'FETCH_MEDIA_SUCCESS',
	FETCH_MEDIA_ERROR: 'FETCH_MEDIA_ERROR',
};
