export const STORE_NAME = 'foldsnap/folders';

export const ACTION_TYPES = {
	FETCH_FOLDERS_START: 'FETCH_FOLDERS_START',
	FETCH_FOLDERS_SUCCESS: 'FETCH_FOLDERS_SUCCESS',
	FETCH_FOLDERS_ERROR: 'FETCH_FOLDERS_ERROR',

	SET_SELECTED_FOLDER: 'SET_SELECTED_FOLDER',
	SET_SEARCH_QUERY: 'SET_SEARCH_QUERY',

	FETCH_MEDIA_START: 'FETCH_MEDIA_START',
	FETCH_MEDIA_SUCCESS: 'FETCH_MEDIA_SUCCESS',
	FETCH_MEDIA_ERROR: 'FETCH_MEDIA_ERROR',
};
